services:
  app:
    build: .
    ports:
      - 3003:3000
    volumes:
      - .:/app
      - docker-node-modules:/app/node_modules
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=docker
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dockerapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  docker-node-modules:
  pgdata:
