services:
  app:
    build: .
    ports:
      - 3003:3000
    volumes:
      - .:/app
      - docker-node-modules:/app/node_modules
    environment:
      - PORT=${PORT}

volumes:
  docker-node-modules:
