services:
  app:
    build: .
    ports:
      - 3003:3000
    volumes:
      - .:/app
      - docker-node-modules:/app/node_modules
    environment:
      - PORT=${PORT}

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dockerapp

volumes:
  docker-node-modules:
